/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.romulo.jogodematematica.gui;

import br.com.romulo.jogodematematica.controle.FabricaDeTabuada;
import java.util.ArrayList;
import javax.swing.JCheckBox;

/**
 *
 * @author romulo
 */
public class ConfiguracaoDoJogo extends javax.swing.JFrame {

    ArrayList<JCheckBox> selectedButtons = new ArrayList<>();
    ArrayList<JCheckBox> selectedOperacoes = new ArrayList<>();
    ArrayList<Integer> todasTabuadas = new ArrayList<>();

    /**
     * Creates new form SelecionarTabuadaEOperacao
     */
    public ConfiguracaoDoJogo() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCBTabuadaTodas = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jCBSubtracao = new javax.swing.JCheckBox();
        jCBAdicao = new javax.swing.JCheckBox();
        jCBMultiplicacao = new javax.swing.JCheckBox();
        jCBDivisao = new javax.swing.JCheckBox();
        jCBOperacaoTodas = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabuada"));

        jCheckBox1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(81, 117, 237));
        jCheckBox1.setText("1");

        jCheckBox2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(81, 117, 237));
        jCheckBox2.setText("2");

        jCheckBox3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(81, 117, 237));
        jCheckBox3.setText("3");

        jCheckBox4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(81, 117, 237));
        jCheckBox4.setText("4");

        jCheckBox5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(81, 117, 237));
        jCheckBox5.setText("5");

        jCheckBox6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(81, 117, 237));
        jCheckBox6.setText("6");

        jCheckBox7.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(81, 117, 237));
        jCheckBox7.setText("7");

        jCheckBox8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(81, 117, 237));
        jCheckBox8.setText("8");

        jCheckBox9.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(81, 117, 237));
        jCheckBox9.setText("9");

        jCheckBox10.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(81, 117, 237));
        jCheckBox10.setText("10");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCBTabuadaTodas.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jCBTabuadaTodas.setForeground(java.awt.Color.green);
        jCBTabuadaTodas.setText("Todas");
        jCBTabuadaTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTabuadaTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox10))
                        .addGap(80, 80, 80))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCBTabuadaTodas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jCBTabuadaTodas))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Operação"));

        jCBSubtracao.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCBSubtracao.setForeground(new java.awt.Color(255, 250, 78));
        jCBSubtracao.setText("Subtração");
        jCBSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSubtracaoActionPerformed(evt);
            }
        });

        jCBAdicao.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCBAdicao.setForeground(new java.awt.Color(255, 250, 78));
        jCBAdicao.setText("Adição");

        jCBMultiplicacao.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCBMultiplicacao.setForeground(new java.awt.Color(255, 250, 78));
        jCBMultiplicacao.setText("Multiplicação");

        jCBDivisao.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCBDivisao.setForeground(new java.awt.Color(255, 250, 78));
        jCBDivisao.setText("Divisão");

        jCBOperacaoTodas.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jCBOperacaoTodas.setForeground(java.awt.Color.green);
        jCBOperacaoTodas.setText("Todas");
        jCBOperacaoTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBOperacaoTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBSubtracao)
                            .addComponent(jCBAdicao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBMultiplicacao)
                            .addComponent(jCBDivisao))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCBOperacaoTodas)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBSubtracao)
                    .addComponent(jCBMultiplicacao))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBAdicao)
                    .addComponent(jCBDivisao))
                .addGap(18, 18, 18)
                .addComponent(jCBOperacaoTodas)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(121, 242, 1));
        jLabel1.setText("Opções de Jogo");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 108, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // Tudo o que o jogo precisa para funcionar.
//        new FabricaDeTabuada().setNumerosDeTabuadas(capturarValoresParaTabuada());
//        new FabricaDeTabuada().setOperacoes(capturaOperacaoMatematica());
        
        new FabricaDeTabuada().setNumerosDeTabuadas(capturarValoresParaTabuada());
        new FabricaDeTabuada().setOperacoes(capturaOperacaoMatematica());
        
        dispose();
        new TelaJogo().setVisible(true);
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCBTabuadaTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTabuadaTodasActionPerformed
        //ao clicar dixa as outras opções inselecionaveis
        todasTabuadasSelecionadas();

    }//GEN-LAST:event_jCBTabuadaTodasActionPerformed

    private void jCBSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSubtracaoActionPerformed


    }//GEN-LAST:event_jCBSubtracaoActionPerformed

    private void jCBOperacaoTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBOperacaoTodasActionPerformed
        todasOperacoesSelecionadas();
    }//GEN-LAST:event_jCBOperacaoTodasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracaoDoJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracaoDoJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCBAdicao;
    private javax.swing.JCheckBox jCBDivisao;
    private javax.swing.JCheckBox jCBMultiplicacao;
    private javax.swing.JCheckBox jCBOperacaoTodas;
    private javax.swing.JCheckBox jCBSubtracao;
    private javax.swing.JCheckBox jCBTabuadaTodas;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    public ArrayList<String> capturaOperacaoMatematica() {

        criaListaBotoesOperacoes();

        if (todasOperacoesSelecionadas()) {
            return operacoes();
        }
        ArrayList<String> operacoes = new ArrayList<String>();
        for (int i = 0; i < 4; i++) {
            if (selectedOperacoes.get(i).isSelected()) {
                if (selectedOperacoes.get(i) == jCBAdicao) {
                    operacoes.add("+");
                }
                if (selectedOperacoes.get(i) == jCBSubtracao) {
                    operacoes.add("-");
                }
                if (selectedOperacoes.get(i) == jCBMultiplicacao) {
                    operacoes.add("*");
                }
                if (selectedOperacoes.get(i) == jCBDivisao) {
                    operacoes.add("/");
                }

            }
        }

        for (String i : operacoes) {
            System.out.println("Operacoes selecionado(s): " + i);
        }
        return operacoes;
    }

    public ArrayList<Integer> capturarValoresParaTabuada() {

        criaListaBotoesTabuada();
        //Captura todos os botoes selecionados.
        //armazena em @tabuada o numero da tabuada que se quer responder
        //

        if (todasTabuadasSelecionadas()) {
            return tabuadas();
        }

        ArrayList<Integer> tabuada = new ArrayList<Integer>();
        for (int i = 0; i < 10; i++) {
            if (selectedButtons.get(i).isSelected()) {
                tabuada.add(Integer.parseInt(selectedButtons.get(i).getText()));
            }
        }
        //teste
        for (int i : tabuada) {
            System.out.println("Valor(es) selecionado(s): " + i);
        }

        return tabuada;

    }

    public void criaListaBotoesTabuada() {
        selectedButtons.clear();
        selectedButtons.add(jCheckBox1);
        selectedButtons.add(jCheckBox2);
        selectedButtons.add(jCheckBox3);
        selectedButtons.add(jCheckBox4);
        selectedButtons.add(jCheckBox5);
        selectedButtons.add(jCheckBox6);
        selectedButtons.add(jCheckBox7);
        selectedButtons.add(jCheckBox8);
        selectedButtons.add(jCheckBox9);
        selectedButtons.add(jCheckBox10);
        System.out.println("Tamanho da lista: " + selectedButtons.size());
    }

    public void criaListaBotoesOperacoes() {
        selectedOperacoes.clear();
        selectedOperacoes.add(jCBAdicao);
        selectedOperacoes.add(jCBMultiplicacao);
        selectedOperacoes.add(jCBSubtracao);
        selectedOperacoes.add(jCBDivisao);
    }

    private boolean todasTabuadasSelecionadas() {
        criaListaBotoesTabuada();
        boolean vf = false;
        for (int i = 0; i < 10; i++) {
            if (jCBTabuadaTodas.isSelected()) {
                selectedButtons.get(i).setSelected(false);
                selectedButtons.get(i).setEnabled(false);
                vf = true;
            } else {
                selectedButtons.get(i).setEnabled(true);
                vf = false;
            }
        }
        return vf;
    }

    private boolean todasOperacoesSelecionadas() {
        criaListaBotoesOperacoes();
        boolean vf = false;
        for (int i = 0; i < 4; i++) {
            if (jCBOperacaoTodas.isSelected()) {
                selectedOperacoes.get(i).setSelected(false);
                selectedOperacoes.get(i).setEnabled(false);
                vf = true;
            } else {
                selectedOperacoes.get(i).setEnabled(true);
                vf = false;
            }
        }
        return vf;
    }

    private ArrayList<String> operacoes() {
        ArrayList<String> operacoes = new ArrayList<>();
        operacoes.add("+");
        operacoes.add("-");
        operacoes.add("*");
        operacoes.add("/");

        return operacoes;
    }

    private ArrayList<Integer> tabuadas() {
        ArrayList<Integer> tabuadas = new ArrayList<>();

        for (int i = 1; i < 11; i++) {
            tabuadas.add(i);
        }
        return tabuadas;
    }

}
